//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
// 
namespace FrontDesk.Applications.Submission.UserService {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UserDataServiceSoap", Namespace="http://FrontDesk/WebServices")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DataComponent))]
    public class UserDataService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        public ServiceTicket ServiceTicketValue;
        
        /// <remarks/>
        public UserDataService() {
            this.Url = "http://localhost/FrontDeskServices/userdatasvc.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ServiceTicketValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://FrontDesk/WebServices/GetCourses", RequestNamespace="http://FrontDesk/WebServices", ResponseNamespace="http://FrontDesk/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Course[] GetCourses(string username) {
            object[] results = this.Invoke("GetCourses", new object[] {
                        username});
            return ((Course[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetCourses(string username, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetCourses", new object[] {
                        username}, callback, asyncState);
        }
        
        /// <remarks/>
        public Course[] EndGetCourses(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Course[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ServiceTicketValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://FrontDesk/WebServices/GetGroups", RequestNamespace="http://FrontDesk/WebServices", ResponseNamespace="http://FrontDesk/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Group[] GetGroups(string username, int asstID) {
            object[] results = this.Invoke("GetGroups", new object[] {
                        username,
                        asstID});
            return ((Group[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetGroups(string username, int asstID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetGroups", new object[] {
                        username,
                        asstID}, callback, asyncState);
        }
        
        /// <remarks/>
        public Group[] EndGetGroups(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Group[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ServiceTicketValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://FrontDesk/WebServices/GetInfo", RequestNamespace="http://FrontDesk/WebServices", ResponseNamespace="http://FrontDesk/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public User GetInfo(string username) {
            object[] results = this.Invoke("GetInfo", new object[] {
                        username});
            return ((User)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetInfo(string username, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetInfo", new object[] {
                        username}, callback, asyncState);
        }
        
        /// <remarks/>
        public User EndGetInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((User)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://FrontDesk/WebServices/Authenticate", RequestNamespace="http://FrontDesk/WebServices", ResponseNamespace="http://FrontDesk/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceTicket Authenticate(string username, string password) {
            object[] results = this.Invoke("Authenticate", new object[] {
                        username,
                        password});
            return ((ServiceTicket)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAuthenticate(string username, string password, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Authenticate", new object[] {
                        username,
                        password}, callback, asyncState);
        }
        
        /// <remarks/>
        public ServiceTicket EndAuthenticate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ServiceTicket)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ServiceTicketValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://FrontDesk/WebServices/Logout", RequestNamespace="http://FrontDesk/WebServices", ResponseNamespace="http://FrontDesk/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Logout() {
            this.Invoke("Logout", new object[0]);
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLogout(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Logout", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public void EndLogout(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FrontDesk/WebServices")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://FrontDesk/WebServices", IsNullable=false)]
    public class ServiceTicket : System.Web.Services.Protocols.SoapHeader {
        
        /// <remarks/>
        public string Username;
        
        /// <remarks/>
        public System.Guid Ident;
        
        /// <remarks/>
        public string HostAddress;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FrontDesk/WebServices")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Principal))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(User))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Group))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Course))]
    public abstract class DataComponent {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FrontDesk/WebServices")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(User))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Group))]
    public class Principal : DataComponent {
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public int PrincipalID;
        
        /// <remarks/>
        public int Type;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FrontDesk/WebServices")]
    public class User : Principal {
        
        /// <remarks/>
        public string UserName;
        
        /// <remarks/>
        public string FirstName;
        
        /// <remarks/>
        public string LastName;
        
        /// <remarks/>
        public string Email;
        
        /// <remarks/>
        public System.DateTime LastLogin;
        
        /// <remarks/>
        public bool Admin;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FrontDesk/WebServices")]
    public class Group : Principal {
        
        /// <remarks/>
        public int AsstID;
        
        /// <remarks/>
        public string Creator;
        
        /// <remarks/>
        public System.DateTime Creation;
        
        /// <remarks/>
        public string GroupName;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FrontDesk/WebServices")]
    public class Course : DataComponent {
        
        /// <remarks/>
        public int ID;
        
        /// <remarks/>
        public int ContentID;
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public string Number;
    }
}
