using System;

using FrontDesk.Common;

namespace FrontDesk.Data.Access {

	/// <summary>
	/// An error generated by the data access layer
	/// </summary>
	public class DataAccessException : CustomException {
		public DataAccessException() : base("There was an error in the last request") { }
		public DataAccessException(string msg) : base(msg) { }
	}
}
