//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
// 
namespace FrontDesk.Testing.Authentication {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AuthenticateServiceSoap", Namespace="http://FrontDesk/WebServices")]
    public class AuthenticateService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        public ServiceTicket ServiceTicketValue;
        
        /// <remarks/>
        public AuthenticateService() {
            this.Url = "http://localhost/FrontDeskServices/authsvc.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://FrontDesk/WebServices/Authenticate", RequestNamespace="http://FrontDesk/WebServices", ResponseNamespace="http://FrontDesk/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceTicket Authenticate(string username, string password) {
            object[] results = this.Invoke("Authenticate", new object[] {
                        username,
                        password});
            return ((ServiceTicket)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAuthenticate(string username, string password, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Authenticate", new object[] {
                        username,
                        password}, callback, asyncState);
        }
        
        /// <remarks/>
        public ServiceTicket EndAuthenticate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ServiceTicket)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ServiceTicketValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://FrontDesk/WebServices/Logout", RequestNamespace="http://FrontDesk/WebServices", ResponseNamespace="http://FrontDesk/WebServices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Logout() {
            this.Invoke("Logout", new object[0]);
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLogout(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Logout", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public void EndLogout(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FrontDesk/WebServices")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://FrontDesk/WebServices", IsNullable=false)]
    public class ServiceTicket : System.Web.Services.Protocols.SoapHeader {
        
        /// <remarks/>
        public string Username;
        
        /// <remarks/>
        public System.Guid Ident;
        
        /// <remarks/>
        public string HostAddress;
    }
}
